apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave1
  namespace: graduation-namespace
  labels:
    app: slave1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave1
  template:
    metadata:
      labels:
        app: slave1
    spec:
      serviceAccountName: jenkins-admin
      automountServiceAccountToken: true
      containers:
      - name: slave1
        image: ahmedmongey/graduation-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
        volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker-sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
---
apiVersion: v1
kind: Service
metadata:
  name: slave1-svc
  namespace: graduation-namespace
spec:
  selector:
    app: slave1
  ports:
  - port: 22
    targetPort: 22
    protocol: TCP

